# Generated by Django 5.2.4 on 2025-08-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="date_of_payment",
            field=models.DateField(
                help_text="Введите дату платежа", verbose_name="Дата оплаты"
            ),
        ),
    ]
