# Generated by Django 5.2.4 on 2025-08-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
