# Generated by Django 5.2.4 on 2025-08-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_payment_url_payments_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
